from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from shopping_intel.opportunity import (
    apply_opportunity_trends,
    read_opportunity_history,
    score_opportunities,
    snapshot_date_from_analysis,
    update_opportunity_history,
    write_opportunity_reports,
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate AI opportunity ranking from an analysis report.")
    parser.add_argument(
        "--analysis",
        default="reports/realtime-ai/analysis.json",
        help="Path to analysis.json generated by the monitor.",
    )
    parser.add_argument(
        "--out",
        default="reports/opportunity-radar",
        help="Output directory for opportunity reports.",
    )
    parser.add_argument(
        "--history",
        default="data/history/opportunity_history.csv",
        help="CSV file used to store daily opportunity ranking snapshots.",
    )
    parser.add_argument(
        "--snapshot-date",
        default="",
        help="Override snapshot date in YYYY-MM-DD format. Defaults to analysis.generated_at.",
    )
    args = parser.parse_args()

    analysis_path = resolve(args.analysis)
    analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
    history_path = resolve(args.history)
    snapshot_date = args.snapshot_date or snapshot_date_from_analysis(analysis)
    history = read_opportunity_history(history_path)
    opportunities = score_opportunities(analysis)
    apply_opportunity_trends(opportunities, history, snapshot_date)
    paths = write_opportunity_reports(opportunities, resolve(args.out))
    update_opportunity_history(history_path, history, opportunities, snapshot_date)

    print("Opportunity report generated")
    print(f"Snapshot date: {snapshot_date}")
    print(f"Items: {len(opportunities)}")
    if opportunities:
        print(f"Top opportunity: {opportunities[0]['query']} ({opportunities[0]['score']})")
    print(f"Markdown: {paths['markdown']}")
    print(f"CSV: {paths['csv']}")
    print(f"JSON: {paths['json']}")
    print(f"History: {history_path}")
    return 0


def resolve(path: str) -> Path:
    candidate = Path(path)
    return candidate if candidate.is_absolute() else ROOT / candidate


if __name__ == "__main__":
    raise SystemExit(main())
