from __future__ import annotations

import argparse
import csv
import gzip
import http.client
import json
import os
import re
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from shopping_intel.analysis import analyze
from shopping_intel.config import load_config, resolve_path
from shopping_intel.models import Product, SearchResult
from shopping_intel.report import write_reports
from shopping_intel.signals import SIGNAL_COLUMNS, enrich_record

USER_AGENT = "shopping-intel-monitor/0.2 (+public APIs only)"
ENV_LOADED = False
REQUEST_TIMEOUT_SECONDS = 40
RETRY_ATTEMPTS = 3
GITHUB_ISSUE_FILTER_CONFIG: dict[str, Any] = {}
FETCH_CACHE: dict[str, Any] = {}

DEFAULT_GITHUB_ISSUE_FILTER_CONFIG = {
    "enabled": True,
    "overfetch_factor": 10,
    "max_fetch_per_query": 50,
    "keep_if_comments_at_least": 3,
    "require_demand_hint": True,
}

GITHUB_ISSUE_BOT_AUTHOR_PATTERNS = [
    r"\[bot\]$",
    r"^dependabot",
    r"^renovate",
    r"^github-actions",
    r"^pre-commit-ci",
    r"^snyk-bot",
    r"^codecov",
    r"^mergify",
]

GITHUB_ISSUE_HARD_NOISE_PATTERNS = [
    r"generated by ai during triage",
    r"\bagent brief\b",
    r"\[supervisor:",
    r"\bsource:health-dashboard\b",
    r"\borigin:worker\b",
    r"\bready-for-agent\b",
    r"\bsandcastle\b",
    r"^\s*(chore|ci|build|test|tests|lint|format|docs)(?:\([^)]+\))?\s*[:\-]",
    r"\b\d+\s+assigned,\s*\d+\s+workers?\b",
    r"\bworkers?\s+at\s+\d{1,2}:\d{2}\s+utc\b",
]

GITHUB_ISSUE_MAINTENANCE_NOISE_PATTERNS = [
    r"\b(bump|update|upgrade)\b.{0,80}\b(dependenc|deps?\b|package|lockfile|requirements|npm|pip|cargo|gradle|maven|go\.mod|poetry\.lock|package-lock)\b",
    r"\b(chore|ci|build|test|tests|lint|format|docs)(?:\([^)]+\))?\s*[:\-]",
    r"\b(release|version)\b\s+v?\d",
    r"\bflaky\s+tests?\b",
]

GITHUB_ISSUE_NOISE_LABEL_PATTERNS = [
    r"\bdependenc",
    r"\bdeps?\b",
    r"\bci\b",
    r"\bbuild\b",
    r"\btests?\b",
    r"\blint\b",
    r"\brelease\b",
    r"\bversion\b",
    r"\bstale\b",
    r"\bautomated\b",
    r"\bbot\b",
    r"\bsource:health-dashboard\b",
    r"\borigin:worker\b",
    r"\bsupervisor\b",
    r"\bready-for-agent\b",
    r"\bsandcastle\b",
]

GITHUB_ISSUE_DEMAND_HINT_PATTERNS = [
    r"\bbug\b",
    r"\berror\b",
    r"\bcrash",
    r"\bexception\b",
    r"\bsegfault\b",
    r"\bfail",
    r"\bbroken\b",
    r"\bnot working\b",
    r"\bdoes not work\b",
    r"\bcan't\b",
    r"\bcannot\b",
    r"\bmissing\b",
    r"\bneed\b",
    r"\brequest\b",
    r"\bfeature request\b",
    r"\benhancement\b",
    r"\bplease add\b",
    r"\bwould like\b",
    r"\bsupport\b",
    r"\bproblem\b",
    r"\bsecurity\b",
    r"\bvulnerab",
    r"\bcve-\d",
    r"\bpain\b",
    r"\bfeedback\b",
    r"\busers?\s+(need|want|ask|report|complain)",
]

GITHUB_ISSUE_DEMAND_LABEL_PATTERNS = [
    r"\bbug\b",
    r"\benhancement\b",
    r"\bfeature\b",
    r"\brequest\b",
    r"\bfeedback\b",
    r"\bquestion\b",
    r"\bhelp wanted\b",
    r"\busability\b",
    r"\bux\b",
    r"\bsupport\b",
]

SEARCH_COLUMNS = [
    "source",
    "query",
    "title",
    "url",
    "rank",
    "result_count",
    "search_volume",
    "snippet",
    "price",
    "currency",
    "seller",
    "rating",
    "review_count",
    "collected_at",
    *SIGNAL_COLUMNS,
]

PRODUCT_COLUMNS = [
    "source",
    "product_id",
    "title",
    "url",
    "price",
    "currency",
    "seller",
    "category",
    "stock_status",
    "rating",
    "review_count",
    "sales_volume",
    "last_updated",
    "collected_at",
    *SIGNAL_COLUMNS,
]


def main() -> int:
    load_env_file(ROOT / ".env.local")
    parser = argparse.ArgumentParser(description="Realtime AI frontier monitor for public platform signals.")
    parser.add_argument("--config", default="config.realtime-ai-platforms.json")
    parser.add_argument("--report-out", default="reports/realtime-ai")
    parser.add_argument("--once", action="store_true", help="Collect once and exit. This is the default.")
    parser.add_argument("--watch", action="store_true", help="Keep collecting on an interval.")
    parser.add_argument("--interval-seconds", type=int, default=900)
    parser.add_argument("--max-cycles", type=int, default=0, help="Only used with --watch. 0 means forever.")
    parser.add_argument("--no-report", action="store_true")
    args = parser.parse_args()

    cycles = 0
    while True:
        config = load_config(args.config)
        run_once(config, report_out=args.report_out, write_report=not args.no_report)
        cycles += 1

        if not args.watch:
            break
        if args.max_cycles and cycles >= args.max_cycles:
            break

        print(f"Sleeping {args.interval_seconds} seconds before next collection...")
        time.sleep(args.interval_seconds)

    return 0


def load_env_file(path: Path) -> None:
    global ENV_LOADED
    if ENV_LOADED or not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and value and key not in os.environ:
            os.environ[key] = value
    ENV_LOADED = True


def run_once(config: dict[str, Any], report_out: str, write_report: bool = True) -> None:
    base_dir = Path(config["_base_dir"])
    collector_config = config.get("collector") or {}
    global REQUEST_TIMEOUT_SECONDS, RETRY_ATTEMPTS, GITHUB_ISSUE_FILTER_CONFIG
    REQUEST_TIMEOUT_SECONDS = int(collector_config.get("request_timeout_seconds") or REQUEST_TIMEOUT_SECONDS)
    RETRY_ATTEMPTS = int(collector_config.get("retry_attempts") or RETRY_ATTEMPTS)
    GITHUB_ISSUE_FILTER_CONFIG = dict(collector_config.get("github_issues_filter") or {})
    enabled_sources = list(collector_config.get("enabled_sources") or [])
    hits_per_source = int(collector_config.get("hits_per_source") or 5)
    delay = float(collector_config.get("request_delay_seconds") or 0)
    source_delays = collector_config.get("request_delay_by_source") or {}
    max_failures_per_source = int(collector_config.get("max_failures_per_source") or 2)
    max_failures_by_source = collector_config.get("max_failures_by_source") or {}
    failure_cooldowns = collector_config.get("failure_cooldown_by_source") or {}
    raw_dir = resolve_path(base_dir, collector_config.get("raw_dir")) or (base_dir / "data/raw/realtime-ai")
    raw_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc)
    collected_at = timestamp.date().isoformat()
    stamp = timestamp.strftime("%Y%m%dT%H%M%SZ")

    search_rows: list[dict[str, Any]] = []
    product_rows: list[dict[str, Any]] = []
    health_rows: list[dict[str, Any]] = []
    failure_counts: dict[str, int] = {}

    for query_config in config.get("queries") or []:
        term = str(query_config.get("term") or "").strip()
        if not term:
            continue
        for source_name in enabled_sources:
            collector = COLLECTORS.get(source_name)
            if collector is None:
                print(f"Skip unsupported source: {source_name}")
                health_rows.append(
                    source_health(source_name, term, "unsupported", 0, 0, 0, "unsupported source")
                )
                continue
            failure_limit = source_failure_limit(source_name, max_failures_per_source, max_failures_by_source)
            if failure_counts.get(source_name, 0) >= failure_limit:
                print(f"{source_name}: {term} skipped after repeated failures")
                health_rows.append(
                    source_health(source_name, term, "skipped", 0, 0, 0, "skipped after repeated failures")
                )
                continue
            started = time.perf_counter()
            try:
                search, products, raw_payload = collector(term, hits_per_source, collected_at)
                search_rows.extend(search)
                product_rows.extend(products)
                write_raw(raw_dir, stamp, source_name, term, raw_payload)
                duration = round(time.perf_counter() - started, 3)
                health_rows.append(source_health(source_name, term, "ok", len(search), len(products), duration))
                print(f"{source_name}: {term} -> search rows {len(search)}, products {len(products)}")
            except Exception as exc:
                duration = round(time.perf_counter() - started, 3)
                failure_counts[source_name] = failure_counts.get(source_name, 0) + 1
                health_rows.append(source_health(source_name, term, "failed", 0, 0, duration, str(exc)))
                print(f"{source_name}: {term} failed: {exc}")
                cooldown_seconds = source_delay_seconds(source_name, 0, failure_cooldowns)
                if cooldown_seconds:
                    print(f"{source_name}: cooling down {cooldown_seconds}s after failure")
                    time.sleep(cooldown_seconds)
            sleep_seconds = source_delay_seconds(source_name, delay, source_delays)
            if sleep_seconds:
                time.sleep(sleep_seconds)

    external_config = collector_config.get("external_imports") or {}
    external_search_path = resolve_path(base_dir, external_config.get("search_results_path"))
    external_product_path = resolve_path(base_dir, external_config.get("products_path"))
    external_search_rows = read_csv_rows(external_search_path)
    external_product_rows = read_csv_rows(external_product_path)
    if external_search_rows or external_product_rows:
        search_rows.extend(external_search_rows)
        product_rows.extend(external_product_rows)
        health_rows.append(
            source_health(
                "external_imports",
                "*",
                "ok",
                len(external_search_rows),
                len(external_product_rows),
                0,
            )
        )
        print(
            "external_imports: "
            f"search rows {len(external_search_rows)}, products {len(external_product_rows)}"
        )

    search_path = resolve_path(base_dir, collector_config.get("search_results_path")) or (
        base_dir / "data/search_results.realtime-ai.csv"
    )
    product_path = resolve_path(base_dir, collector_config.get("products_path")) or (
        base_dir / "data/products.realtime-ai.csv"
    )
    write_csv(search_path, SEARCH_COLUMNS, search_rows)
    write_csv(product_path, PRODUCT_COLUMNS, product_rows)

    if write_report:
        search_results = [SearchResult.from_record(row, default_source=row.get("source", "")) for row in search_rows]
        products = [Product.from_record(row, default_source=row.get("source", "")) for row in product_rows]
        result = analyze(config, search_results, products, now=timestamp)
        paths = write_reports(result, base_dir / report_out)
        print(f"Report: {paths['markdown']}")

    write_health_report(health_rows, base_dir / report_out)
    print(f"Collected {len(search_rows)} search rows and {len(product_rows)} product rows.")


def collect_github(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {"q": term, "sort": "stars", "order": "desc", "per_page": limit}
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": USER_AGENT,
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {os.environ['GITHUB_TOKEN']}"
    payload = get_json(
        "https://api.github.com/search/repositories?" + urllib.parse.urlencode(params),
        headers=headers,
    )
    total = payload.get("total_count") or 0
    search_rows = []
    product_rows = []
    for rank, item in enumerate(payload.get("items") or [], start=1):
        owner = item.get("owner") or {}
        title = item.get("full_name") or item.get("name") or ""
        url = item.get("html_url") or ""
        search_rows.append(
            search_row(
                "github",
                term,
                title,
                url,
                rank,
                total,
                item.get("description") or "",
                seller=owner.get("login") or "",
                review_count=item.get("stargazers_count") or "",
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "github",
                title,
                title,
                url,
                category="repository",
                stock_status="public",
                seller=owner.get("login") or "",
                review_count=item.get("stargazers_count") or "",
                sales_volume=item.get("forks_count") or "",
                last_updated=item.get("pushed_at") or item.get("updated_at") or "",
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_github_issues(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    filter_config = github_issue_filter_config()
    fetch_limit = github_issue_fetch_limit(limit, filter_config)
    params = {
        "q": f'"{term}" is:issue in:title,body',
        "sort": "updated",
        "order": "desc",
        "per_page": fetch_limit,
    }
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": USER_AGENT,
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {os.environ['GITHUB_TOKEN']}"
    payload = get_json(
        "https://api.github.com/search/issues?" + urllib.parse.urlencode(params),
        headers=headers,
    )
    total = payload.get("total_count") or 0
    items = list(payload.get("items") or [])
    filtered_items, skipped_items = filter_github_issue_items(items, filter_config)
    effective_total = github_issue_effective_total(total, len(items), len(filtered_items), filter_config)
    payload = dict(payload)
    payload["filter_summary"] = {
        "enabled": bool(filter_config.get("enabled", True)),
        "inspected": len(items),
        "kept": len(filtered_items),
        "skipped": len(skipped_items),
        "api_total_count": total,
        "effective_total_count": effective_total,
        "skipped_items": skipped_items[:20],
    }
    if filter_config.get("enabled", True):
        print(
            f"github_issues: {term} filtered {len(skipped_items)}/{len(items)} "
            f"issues; effective total {effective_total} from API total {total}"
        )
    search_rows = []
    product_rows = []
    for rank, item in enumerate(filtered_items[:limit], start=1):
        title = item.get("title") or ""
        url = item.get("html_url") or ""
        user = item.get("user") or {}
        comments = item.get("comments") or 0
        repo = github_repo_from_issue(item)
        snippet = clean(item.get("body") or "")[:500]
        issue_id = str(item.get("id") or item.get("number") or url)
        search_rows.append(
            search_row(
                "github_issues",
                term,
                title,
                url,
                rank,
                effective_total,
                snippet,
                seller=repo or user.get("login") or "",
                review_count=comments,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "github_issues",
                issue_id,
                title,
                url,
                category="github_issue_feedback",
                stock_status=item.get("state") or "open",
                seller=repo or user.get("login") or "",
                review_count=comments,
                sales_volume=1,
                last_updated=item.get("updated_at") or item.get("created_at") or "",
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_producthunt(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {"query": term, "hitsPerPage": limit}
    payload = get_json(
        "https://0h4smabbsg-dsn.algolia.net/1/indexes/Post_production?" + urllib.parse.urlencode(params),
        headers={
            "User-Agent": USER_AGENT,
            "X-Algolia-API-Key": "9670d2d619b9d07859448d7628eea5f3",
            "X-Algolia-Application-Id": "0H4SMABBSG",
        },
    )
    total = payload.get("nbHits") or 0
    search_rows = []
    product_rows = []
    for rank, item in enumerate(payload.get("hits") or [], start=1):
        title = item.get("name") or ""
        url = producthunt_url(item)
        user = item.get("user") or {}
        search_rows.append(
            search_row(
                "producthunt",
                term,
                title,
                url,
                rank,
                total,
                item.get("tagline") or "",
                seller=user.get("username") or "",
                review_count=item.get("vote_count") or "",
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "producthunt",
                item.get("objectID") or str(item.get("id") or ""),
                title,
                url,
                category="producthunt_post",
                stock_status=item.get("product_state") or "listed",
                seller=user.get("username") or "",
                review_count=item.get("vote_count") or "",
                sales_volume=item.get("comments_count") or "",
                last_updated=item.get("featured_at") or item.get("created_at") or "",
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_arxiv(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {
        "search_query": f'all:"{term}"',
        "start": 0,
        "max_results": limit,
        "sortBy": "submittedDate",
        "sortOrder": "descending",
    }
    text = get_text("https://export.arxiv.org/api/query?" + urllib.parse.urlencode(params))
    root = ET.fromstring(text)
    ns = {
        "atom": "http://www.w3.org/2005/Atom",
        "opensearch": "http://a9.com/-/spec/opensearch/1.1/",
    }
    total = int(root.findtext("opensearch:totalResults", default="0", namespaces=ns) or 0)
    search_rows = []
    product_rows = []
    for rank, entry in enumerate(root.findall("atom:entry", ns), start=1):
        title = clean(entry.findtext("atom:title", default="", namespaces=ns))
        summary = clean(entry.findtext("atom:summary", default="", namespaces=ns))
        url = entry.findtext("atom:id", default="", namespaces=ns)
        updated = entry.findtext("atom:updated", default="", namespaces=ns)
        authors = ", ".join(
            clean(author.findtext("atom:name", default="", namespaces=ns))
            for author in entry.findall("atom:author", ns)
        )
        search_rows.append(
            search_row("arxiv", term, title, url, rank, total, summary, seller=authors, collected_at=collected_at)
        )
        product_rows.append(
            product_row(
                "arxiv",
                url.rsplit("/", 1)[-1],
                title,
                url,
                category="research_paper",
                stock_status="published",
                seller=authors,
                last_updated=updated,
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, {"xml": text}


def collect_huggingface_models(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {"search": term, "sort": "downloads", "direction": "-1", "limit": limit}
    payload = get_json("https://huggingface.co/api/models?" + urllib.parse.urlencode(params))
    return huggingface_rows("huggingface_models", term, payload, limit, collected_at, category="hf_model")


def collect_huggingface_spaces(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {"search": term, "sort": "likes", "direction": "-1", "limit": limit}
    payload = get_json("https://huggingface.co/api/spaces?" + urllib.parse.urlencode(params))
    return huggingface_rows("huggingface_spaces", term, payload, limit, collected_at, category="hf_space")


def huggingface_rows(
    source: str,
    term: str,
    payload: list[dict[str, Any]],
    limit: int,
    collected_at: str,
    category: str,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    # Lightweight Hugging Face search returns a page, not an exact total count.
    total = len(payload)
    search_rows = []
    product_rows = []
    for rank, item in enumerate(payload[:limit], start=1):
        item_id = item.get("id") or item.get("modelId") or item.get("name") or ""
        url_prefix = "https://huggingface.co/spaces/" if source == "huggingface_spaces" else "https://huggingface.co/"
        url = url_prefix + item_id
        snippet = " ".join(str(tag) for tag in item.get("tags") or [])[:300]
        downloads = item.get("downloads") or ""
        likes = item.get("likes") or ""
        search_rows.append(
            search_row(
                source,
                term,
                item_id,
                url,
                rank,
                total,
                snippet,
                review_count=likes,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                source,
                item_id,
                item_id,
                url,
                category=category,
                stock_status="public",
                review_count=likes,
                sales_volume=downloads,
                last_updated=item.get("lastModified") or item.get("updatedAt") or item.get("createdAt") or "",
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_hackernews(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {"query": term, "tags": "story", "hitsPerPage": limit}
    payload = get_json("https://hn.algolia.com/api/v1/search_by_date?" + urllib.parse.urlencode(params))
    total = payload.get("nbHits") or 0
    search_rows = []
    product_rows = []
    for rank, item in enumerate(payload.get("hits") or [], start=1):
        title = item.get("title") or item.get("story_title") or ""
        object_id = item.get("objectID") or ""
        url = item.get("url") or f"https://news.ycombinator.com/item?id={object_id}"
        search_rows.append(
            search_row(
                "hackernews",
                term,
                title,
                url,
                rank,
                total,
                item.get("comment_text") or "",
                seller=item.get("author") or "",
                review_count=item.get("points") or "",
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "hackernews",
                object_id,
                title,
                url,
                category="hn_story",
                stock_status="public",
                seller=item.get("author") or "",
                review_count=item.get("points") or "",
                sales_volume=item.get("num_comments") or "",
                last_updated=item.get("created_at") or "",
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_reddit(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {"q": term, "sort": "new", "limit": limit, "raw_json": 1}
    payload = get_json(
        "https://www.reddit.com/search.json?" + urllib.parse.urlencode(params),
        headers={"User-Agent": USER_AGENT},
    )
    children = (payload.get("data") or {}).get("children") or []
    total = int((payload.get("data") or {}).get("dist") or len(children))
    search_rows = []
    product_rows = []
    for rank, child in enumerate(children[:limit], start=1):
        item = child.get("data") or {}
        title = item.get("title") or ""
        permalink = item.get("permalink") or ""
        url = "https://www.reddit.com" + permalink if permalink.startswith("/") else item.get("url") or ""
        author = item.get("author") or ""
        created = _timestamp_to_iso(item.get("created_utc"))
        snippet = clean(item.get("selftext") or item.get("subreddit_name_prefixed") or "")
        search_rows.append(
            search_row(
                "reddit",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=author,
                review_count=item.get("score") or "",
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "reddit",
                item.get("id") or "",
                title,
                url,
                category="reddit_post",
                stock_status="public",
                seller=author,
                review_count=item.get("score") or "",
                sales_volume=item.get("num_comments") or "",
                last_updated=created,
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_google_news(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {"q": term, "hl": "en-US", "gl": "US", "ceid": "US:en"}
    text = get_text("https://news.google.com/rss/search?" + urllib.parse.urlencode(params))
    root = ET.fromstring(text)
    items = root.findall(".//item")
    total = len(items)
    search_rows = []
    product_rows = []
    for rank, item in enumerate(items[:limit], start=1):
        title = clean(item.findtext("title", default=""))
        url = item.findtext("link", default="")
        publisher = item.findtext("source", default="")
        published = _parse_rss_date(item.findtext("pubDate", default=""))
        snippet = clean(_strip_tags(item.findtext("description", default="")))
        search_rows.append(
            search_row(
                "google_news",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=publisher,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "google_news",
                url or f"{term}-{rank}",
                title,
                url,
                category="news_article",
                stock_status="public",
                seller=publisher,
                last_updated=published,
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, {"rss": text}


def collect_ai_dev_jobs(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {
        "q": term,
        "limit": min(max(limit, 1), 50),
        "posted_within_days": 90,
    }
    payload = get_json("https://aidevboard.com/api/v1/jobs?" + urllib.parse.urlencode(params))
    jobs = payload.get("jobs") or []
    total = int(payload.get("total") or len(jobs))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(jobs[:limit], start=1):
        title = item.get("title") or ""
        company = item.get("company_name") or ""
        url = item.get("url") or item.get("apply_url") or ""
        salary_min = item.get("salary_min") or ""
        salary_max = item.get("salary_max") or ""
        tags = ", ".join(str(tag) for tag in item.get("tags") or [])
        snippet_parts = [
            clean(str(item.get("description") or ""))[:350],
            f"tags: {tags}" if tags else "",
            f"salary: {salary_min}-{salary_max} USD" if salary_min or salary_max else "",
            item.get("location") or "",
            item.get("workplace") or "",
        ]
        snippet = " | ".join(part for part in snippet_parts if part)
        quality_score = item.get("quality_score") or ""
        search_rows.append(
            search_row(
                "ai_dev_jobs",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=company,
                review_count=quality_score,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "ai_dev_jobs",
                item.get("id") or item.get("slug") or url,
                title,
                url,
                category="ai_job",
                stock_status=item.get("status") or "active",
                seller=company,
                review_count=quality_score,
                sales_volume=salary_max or salary_min or "",
                last_updated=item.get("published_at") or item.get("updated_at") or item.get("created_at") or "",
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_patentsview(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    api_key = os.environ.get("PATENTSVIEW_API_KEY")
    if not api_key:
        return [], [], {"skipped": "Set PATENTSVIEW_API_KEY to enable PatentsView Search API collection."}

    body = json.dumps(
        {
            "query": {"_text_any": {"patent_title": term}},
            "fields": ["patent_id", "patent_title", "patent_date", "patent_abstract", "patent_num_cited_by_us_patents"],
            "options": {"size": min(max(limit, 1), 50)},
        }
    ).encode("utf-8")
    request = urllib.request.Request(
        "https://search.patentsview.org/api/v1/patent/",
        data=body,
        headers={
            "Content-Type": "application/json",
            "X-Api-Key": api_key,
            "User-Agent": USER_AGENT,
        },
        method="POST",
    )
    payload = get_json_request(request)
    patents = payload_items(payload, "patents", "data", "results")
    total = payload_total(payload, len(patents))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(patents[:limit], start=1):
        patent_id = str(first_present(item, "patent_id", "id", "patent_number"))
        title = str(first_present(item, "patent_title", "title", "invention_title"))
        url = f"https://patents.google.com/patent/US{patent_id}" if patent_id else ""
        citations = first_present(item, "patent_num_cited_by_us_patents", "num_cited_by_us_patents", "cited_by_count")
        updated = str(first_present(item, "patent_date", "date", "publication_date"))
        snippet = clean(str(first_present(item, "patent_abstract", "abstract", "description")))[:500]
        search_rows.append(
            search_row(
                "patentsview",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller="USPTO / PatentsView",
                review_count=citations,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "patentsview",
                patent_id or url,
                title,
                url,
                category="patent",
                stock_status="published",
                seller="USPTO / PatentsView",
                review_count=citations,
                sales_volume=1,
                last_updated=updated,
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_domainsdb(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    api_key = os.environ.get("DOMAINSDB_API_KEY")
    if not api_key:
        return [], [], {"skipped": "Set DOMAINSDB_API_KEY to enable DomainsDB collection."}

    domain_query = domain_search_term(term)
    params = {
        "domain": domain_query,
        "limit": min(max(limit, 1), 50),
        "api_key": api_key,
    }
    payload = get_json(
        "https://api.domainsdb.info/v1/domains/search?" + urllib.parse.urlencode(params),
        headers={"Authorization": f"Bearer {api_key}", "User-Agent": USER_AGENT},
    )
    domains = payload_items(payload, "domains", "data", "results")
    total = payload_total(payload, len(domains))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(domains[:limit], start=1):
        domain = str(first_present(item, "domain", "name", "domain_name", "fqdn"))
        zone = str(first_present(item, "zone", "tld"))
        title = domain if "." in domain or not zone else f"{domain}.{zone}"
        url = f"https://{title}" if title else ""
        country = str(first_present(item, "country", "country_code"))
        ns = first_present(item, "NS", "ns", "nameservers")
        snippet = clean(json.dumps({"country": country, "ns": ns}, ensure_ascii=False))[:500]
        search_rows.append(
            search_row(
                "domainsdb",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=country,
                review_count=1,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "domainsdb",
                title,
                title,
                url,
                category="registered_domain",
                stock_status="registered",
                seller=country,
                review_count=1,
                last_updated=str(first_present(item, "created", "created_date", "updated", "changed")),
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_agentic_engineering_jobs(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {
        "q": term,
        "sort": "newest",
        "limit": min(max(limit * 5, 10), 50),
    }
    payload = get_json(
        "https://agentic-engineering-jobs.com/api/v1/jobs?" + urllib.parse.urlencode(params)
    )
    jobs = payload_items(payload, "data", "jobs", "results")
    meta = payload.get("meta") if isinstance(payload, dict) else {}
    total = payload_total(meta if isinstance(meta, dict) else payload, len(jobs))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(jobs[:limit], start=1):
        title = str(first_present(item, "title", "name"))
        company = str(first_present(item, "companyName", "company", "company_name"))
        slug_value = str(first_present(item, "slug", "id"))
        url = agentic_job_url(item)
        salary_min = first_present(item, "salaryMin", "salary_min")
        salary_max = first_present(item, "salaryMax", "salary_max")
        salary_currency = str(first_present(item, "salaryCurrency", "currency")) or "USD"
        stack = ", ".join(
            str(value)
            for values in (
                item.get("aiInfrastructure") or [],
                item.get("techStackTags") or [],
                item.get("agenticFrameworks") or [],
            )
            for value in values
        )
        snippet_parts = [
            clean(_strip_tags(str(first_present(item, "description", "summary"))))[:350],
            f"stack: {stack}" if stack else "",
            f"salary: {salary_min}-{salary_max} {salary_currency}" if salary_min or salary_max else "",
            str(first_present(item, "location", "city")),
            str(first_present(item, "locationType", "remoteScope", "workplace")),
        ]
        snippet = " | ".join(part for part in snippet_parts if part)
        engagement = safe_int(item.get("viewCount")) + safe_int(item.get("clickCount"))
        search_rows.append(
            search_row(
                "agentic_engineering_jobs",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=company,
                review_count=engagement,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "agentic_engineering_jobs",
                slug_value or url,
                title,
                url,
                category="agentic_ai_job",
                stock_status=str(first_present(item, "employmentType", "status")) or "active",
                seller=company,
                review_count=engagement,
                sales_volume=salary_max or salary_min or "",
                last_updated=str(first_present(item, "postedAt", "featuredAt", "updatedAt", "createdAt")),
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_agentdeals(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {
        "q": term,
        "limit": min(max(limit * 5, 20), 50),
    }
    payload = get_json("https://agentdeals.dev/api/offers?" + urllib.parse.urlencode(params))
    offers = payload_items(payload, "offers", "data", "results")
    total = payload_total(payload, len(offers))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(offers[:limit], start=1):
        vendor = str(first_present(item, "vendor", "name"))
        category = str(first_present(item, "category", "tier"))
        title = f"{vendor} - {first_present(item, 'tier', 'category')}".strip(" -")
        url = str(first_present(item, "url", "source_url"))
        tags = ", ".join(str(tag) for tag in item.get("tags") or [])
        recent_change = item.get("recent_change") or {}
        change_text = ""
        if isinstance(recent_change, dict):
            change_text = clean(str(first_present(recent_change, "summary", "impact", "change_type")))
        snippet = " | ".join(
            part
            for part in (
                clean(str(first_present(item, "description", "summary")))[:350],
                f"tags: {tags}" if tags else "",
                f"risk: {first_present(item, 'risk_level', 'stability')}" if first_present(item, "risk_level", "stability") else "",
                f"recent change: {change_text}" if change_text else "",
            )
            if part
        )
        referral = item.get("referral_program") or {}
        has_referral = 1 if isinstance(referral, dict) and referral.get("available") else 0
        signal = 1 + has_referral + (1 if item.get("expires_soon") else 0)
        search_rows.append(
            search_row(
                "agentdeals",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=vendor,
                review_count=signal,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "agentdeals",
                vendor or url,
                title,
                url,
                category=f"developer_deal:{category}" if category else "developer_deal",
                stock_status=str(first_present(item, "risk_level", "stability")) or "listed",
                seller=vendor,
                review_count=signal,
                sales_volume=max(0, 365 - safe_int(item.get("days_since_verified"))),
                last_updated=str(first_present(item, "verifiedDate", "updatedAt", "createdAt")),
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_oksurf_news(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    payload = get_json_cached("https://ok.surf/api/v1/cors/news-feed")
    items = oksurf_items(payload)
    matches = [
        item for item in items
        if text_matches_query(term, oksurf_text(item), min_tokens=oksurf_min_tokens(term))
    ]
    total = len(matches)
    search_rows = []
    product_rows = []
    for rank, item in enumerate(matches[:limit], start=1):
        title = str(first_present(item, "title", "name"))
        url = str(first_present(item, "link", "url"))
        publisher = str(first_present(item, "source", "publisher"))
        og = item.get("og") or {}
        description = clean(str(first_present(og, "description", "site_name", "title"))) if isinstance(og, dict) else ""
        search_rows.append(
            search_row(
                "oksurf_news",
                term,
                title,
                url,
                rank,
                total,
                description,
                seller=publisher,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "oksurf_news",
                url or f"{term}-{rank}",
                title,
                url,
                category=f"news_article:{item.get('_category', '')}".strip(":"),
                stock_status="public",
                seller=publisher,
                review_count=1,
                last_updated=collected_at,
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, {"matched": matches[: max(limit, 20)], "source": payload}


def collect_api_status_check(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    payload = get_json_cached("https://apistatuscheck.com/api/status")
    apis = payload_items(payload, "apis")
    matches = [item for item in apis if api_status_matches(term, item)]
    total = len(matches)
    search_rows = []
    product_rows = []
    for rank, item in enumerate(matches[:limit], start=1):
        name = str(first_present(item, "name", "slug"))
        status = str(first_present(item, "status", "state"))
        category = str(first_present(item, "category", "type"))
        links = item.get("links") or {}
        page = links.get("page") if isinstance(links, dict) else ""
        url = str(page or f"https://apistatuscheck.com/api/{first_present(item, 'slug', 'name')}")
        incident_weight = api_status_weight(status)
        snippet = f"category: {category} | status: {status}"
        search_rows.append(
            search_row(
                "api_status_check",
                term,
                name,
                url,
                rank,
                total,
                snippet,
                seller=category,
                review_count=incident_weight,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "api_status_check",
                str(first_present(item, "slug", "name")),
                name,
                url,
                category=f"api_status:{category}" if category else "api_status",
                stock_status=status or "unknown",
                seller=category,
                review_count=incident_weight,
                sales_volume=1,
                last_updated=str(first_present(payload, "lastUpdated", "timestamp")),
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_internet_archive(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    params = {
        "q": term,
        "rows": min(max(limit, 1), 50),
        "output": "json",
    }
    field_params = "&".join(
        "fl[]=" + urllib.parse.quote(field)
        for field in ("identifier", "title", "creator", "date", "description", "downloads")
    )
    payload = get_json(
        "https://archive.org/advancedsearch.php?"
        + urllib.parse.urlencode(params)
        + "&"
        + field_params
    )
    response = payload.get("response") if isinstance(payload, dict) else {}
    docs = payload_items(response if isinstance(response, dict) else payload, "docs")
    total = payload_total(response if isinstance(response, dict) else payload, len(docs))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(docs[:limit], start=1):
        identifier = str(first_present(item, "identifier", "id"))
        title = str(first_present(item, "title", "name")) or identifier
        url = f"https://archive.org/details/{identifier}" if identifier else ""
        downloads = first_present(item, "downloads", "download_count")
        creator = archive_creator(item)
        snippet = clean(str(first_present(item, "description", "summary")))[:500]
        search_rows.append(
            search_row(
                "internet_archive",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=creator,
                review_count=downloads,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "internet_archive",
                identifier or url,
                title,
                url,
                category="archive_record",
                stock_status="public",
                seller=creator,
                review_count=downloads,
                sales_volume=downloads,
                last_updated=str(first_present(item, "date", "publicdate", "addeddate")),
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_nvd(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    payload = get_gzip_json_cached("https://nvd.nist.gov/feeds/json/cve/2.0/nvdcve-2.0-recent.json.gz")
    vulnerabilities = payload_items(payload, "vulnerabilities")
    matches = [item for item in vulnerabilities if nvd_matches(term, item)]
    total = len(matches)
    search_rows = []
    product_rows = []
    for rank, item in enumerate(matches[:limit], start=1):
        cve = item.get("cve") or {}
        cve_id = str(first_present(cve, "id"))
        description = nvd_description(cve)
        score, severity = nvd_cvss(cve)
        url = f"https://nvd.nist.gov/vuln/detail/{cve_id}" if cve_id else ""
        refs_payload = cve.get("references") or []
        if isinstance(refs_payload, dict):
            refs = refs_payload.get("referenceData") or []
        else:
            refs = refs_payload
        reference_count = len(refs) if isinstance(refs, list) else 0
        title = f"{cve_id} {severity}".strip()
        search_rows.append(
            search_row(
                "nvd",
                term,
                title,
                url,
                rank,
                total,
                description[:500],
                seller=str(first_present(cve, "sourceIdentifier")),
                review_count=round(score * 10),
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "nvd",
                cve_id or url,
                title,
                url,
                category="cve",
                stock_status=str(first_present(cve, "vulnStatus", "status")) or "published",
                seller=str(first_present(cve, "sourceIdentifier")),
                review_count=round(score * 10),
                sales_volume=reference_count,
                last_updated=str(first_present(cve, "lastModified", "published")),
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, {"matched": matches[: max(limit, 20)], "source": payload}


def collect_devitjobs(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    payload = get_json_cached("https://devitjobs.us/api/jobsLight")
    jobs = payload if isinstance(payload, list) else payload_items(payload, "jobs", "data", "results")
    matches = [item for item in jobs if text_matches_query(term, devitjobs_text(item), min_tokens=devitjobs_min_tokens(term))]
    total = len(matches)
    search_rows = []
    product_rows = []
    for rank, item in enumerate(matches[:limit], start=1):
        title = str(first_present(item, "name", "title"))
        company = str(first_present(item, "company", "companyName"))
        slug_value = str(first_present(item, "jobUrl", "_id", "id"))
        url = devitjobs_url(slug_value)
        salary_from = first_present(item, "annualSalaryFrom", "salaryFrom", "contractRateFrom")
        salary_to = first_present(item, "annualSalaryTo", "salaryTo", "contractRateTo")
        tech = ", ".join(str(value) for value in item.get("technologies") or item.get("technology") or [])
        snippet = " | ".join(
            part
            for part in (
                f"tech: {tech}" if tech else str(first_present(item, "techCategory", "metaCategory")),
                str(first_present(item, "workplace", "remoteType")),
                str(first_present(item, "actualCity", "cityCategory", "stateCategory")),
                f"salary: {salary_from}-{salary_to}" if salary_from or salary_to else "",
            )
            if part
        )
        search_rows.append(
            search_row(
                "devitjobs",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller=company,
                review_count=1,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "devitjobs",
                str(first_present(item, "_id", "id", "jobUrl")),
                title,
                url,
                category="developer_job",
                stock_status="active" if not item.get("isPaused") else "paused",
                seller=company,
                review_count=1,
                sales_volume=salary_to or salary_from or "",
                last_updated=str(first_present(item, "activeFrom", "publishedAt", "updatedAt")),
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_predscope(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    payload = get_json_cached("https://predscope.com/api/markets.json")
    markets = payload_items(payload, "markets", "data", "results")
    matches = [
        item for item in markets
        if text_matches_query(term, predscope_text(item), min_tokens=predscope_min_tokens(term))
    ]
    total = len(matches)
    search_rows = []
    product_rows = []
    for rank, item in enumerate(matches[:limit], start=1):
        title = str(first_present(item, "title", "name"))
        raw_url = str(first_present(item, "url", "link"))
        url = "https://predscope.com" + raw_url if raw_url.startswith("/") else raw_url
        volume = safe_int(item.get("volume")) or safe_int(item.get("volume_24h"))
        top_outcome = predscope_top_outcome(item)
        snippet = " | ".join(
            part
            for part in (
                f"categories: {', '.join(str(value) for value in item.get('categories') or [])}",
                f"top outcome: {top_outcome}" if top_outcome else "",
                f"24h volume: {item.get('volume_24h')}" if item.get("volume_24h") else "",
            )
            if part
        )
        search_rows.append(
            search_row(
                "predscope",
                term,
                title,
                url,
                rank,
                total,
                snippet,
                seller="prediction_market",
                review_count=volume,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "predscope",
                str(first_present(item, "slug", "id", "url")),
                title,
                url,
                category="prediction_market",
                stock_status="active",
                seller="prediction_market",
                review_count=volume,
                sales_volume=safe_int(item.get("liquidity")),
                last_updated=collected_at,
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_youtube(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    api_key = os.environ.get("YOUTUBE_API_KEY")
    if not api_key:
        return [], [], {"skipped": "Set YOUTUBE_API_KEY to enable YouTube Data API collection."}
    params = {
        "part": "snippet",
        "q": term,
        "type": "video",
        "order": "relevance",
        "maxResults": min(max(limit, 1), 50),
        "key": api_key,
    }
    payload = get_json("https://www.googleapis.com/youtube/v3/search?" + urllib.parse.urlencode(params))
    total = int((payload.get("pageInfo") or {}).get("totalResults") or len(payload.get("items") or []))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(payload.get("items") or [], start=1):
        snippet = item.get("snippet") or {}
        video_id = (item.get("id") or {}).get("videoId") or ""
        url = f"https://www.youtube.com/watch?v={video_id}" if video_id else ""
        title = snippet.get("title") or ""
        channel = snippet.get("channelTitle") or ""
        published = snippet.get("publishedAt") or ""
        description = snippet.get("description") or ""
        search_rows.append(
            search_row("youtube", term, title, url, rank, total, description, seller=channel, collected_at=collected_at)
        )
        product_rows.append(
            product_row(
                "youtube",
                video_id,
                title,
                url,
                category="youtube_video",
                stock_status="public",
                seller=channel,
                last_updated=published,
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


def collect_x_recent(term: str, limit: int, collected_at: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]], Any]:
    bearer_token = os.environ.get("X_BEARER_TOKEN") or os.environ.get("TWITTER_BEARER_TOKEN")
    if not bearer_token:
        return [], [], {"skipped": "Set X_BEARER_TOKEN to enable X recent search collection."}
    params = {
        "query": f"{term} lang:en -is:retweet",
        "max_results": min(max(limit, 10), 100),
        "tweet.fields": "created_at,public_metrics,author_id",
    }
    payload = get_json(
        "https://api.x.com/2/tweets/search/recent?" + urllib.parse.urlencode(params),
        headers={"User-Agent": USER_AGENT, "Authorization": f"Bearer {bearer_token}"},
    )
    tweets = payload.get("data") or []
    total = int((payload.get("meta") or {}).get("result_count") or len(tweets))
    search_rows = []
    product_rows = []
    for rank, item in enumerate(tweets[:limit], start=1):
        tweet_id = item.get("id") or ""
        metrics = item.get("public_metrics") or {}
        engagement = sum(int(metrics.get(key) or 0) for key in ("like_count", "reply_count", "retweet_count", "quote_count"))
        url = f"https://x.com/i/web/status/{tweet_id}" if tweet_id else ""
        text = clean(item.get("text") or "")
        search_rows.append(
            search_row(
                "x_recent",
                term,
                text[:120],
                url,
                rank,
                total,
                text,
                seller=item.get("author_id") or "",
                review_count=engagement,
                collected_at=collected_at,
            )
        )
        product_rows.append(
            product_row(
                "x_recent",
                tweet_id,
                text[:120],
                url,
                category="x_tweet",
                stock_status="public",
                seller=item.get("author_id") or "",
                review_count=engagement,
                last_updated=item.get("created_at") or "",
                collected_at=collected_at,
            )
        )
    return search_rows, product_rows, payload


COLLECTORS = {
    "github": collect_github,
    "github_issues": collect_github_issues,
    "producthunt": collect_producthunt,
    "arxiv": collect_arxiv,
    "huggingface_models": collect_huggingface_models,
    "huggingface_spaces": collect_huggingface_spaces,
    "hackernews": collect_hackernews,
    "reddit": collect_reddit,
    "google_news": collect_google_news,
    "ai_dev_jobs": collect_ai_dev_jobs,
    "patentsview": collect_patentsview,
    "domainsdb": collect_domainsdb,
    "agentic_engineering_jobs": collect_agentic_engineering_jobs,
    "agentdeals": collect_agentdeals,
    "oksurf_news": collect_oksurf_news,
    "api_status_check": collect_api_status_check,
    "internet_archive": collect_internet_archive,
    "nvd": collect_nvd,
    "devitjobs": collect_devitjobs,
    "predscope": collect_predscope,
    "youtube": collect_youtube,
    "x_recent": collect_x_recent,
}


def get_json(url: str, headers: dict[str, str] | None = None) -> Any:
    request = urllib.request.Request(url, headers=headers or {"User-Agent": USER_AGENT})
    return get_json_request(request)


def get_json_request(request: urllib.request.Request) -> Any:
    return json.loads(_read_request_bytes_with_retry(request).decode("utf-8"))


def get_text(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    return _read_request_bytes_with_retry(request).decode("utf-8")


def get_json_cached(url: str, headers: dict[str, str] | None = None) -> Any:
    cache_key = f"json:{url}"
    if cache_key not in FETCH_CACHE:
        FETCH_CACHE[cache_key] = get_json(url, headers=headers)
    return FETCH_CACHE[cache_key]


def get_gzip_json_cached(url: str, headers: dict[str, str] | None = None) -> Any:
    cache_key = f"gzip-json:{url}"
    if cache_key not in FETCH_CACHE:
        request = urllib.request.Request(url, headers=headers or {"User-Agent": USER_AGENT})
        FETCH_CACHE[cache_key] = json.loads(gzip.decompress(_read_request_bytes_with_retry(request)).decode("utf-8"))
    return FETCH_CACHE[cache_key]


def _read_request_bytes_with_retry(request: urllib.request.Request, attempts: int = 3) -> bytes:
    attempts = RETRY_ATTEMPTS if attempts == 3 else attempts
    for attempt in range(1, attempts + 1):
        try:
            with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT_SECONDS) as response:
                return response.read()
        except urllib.error.HTTPError as exc:
            if exc.code not in (429, 500, 502, 503, 504) or attempt == attempts:
                raise
            retry_after = exc.headers.get("Retry-After")
            if retry_after and retry_after.isdigit():
                sleep_seconds = min(int(retry_after), 120)
            else:
                sleep_seconds = min(15 * attempt, 90)
            print(f"HTTP {exc.code}; retrying in {sleep_seconds}s...")
            time.sleep(sleep_seconds)
        except (
            urllib.error.URLError,
            TimeoutError,
            ssl.SSLError,
            http.client.IncompleteRead,
            http.client.RemoteDisconnected,
        ) as exc:
            if attempt == attempts:
                raise
            sleep_seconds = min(6 * attempt, 24)
            print(f"Network error {exc}; retrying in {sleep_seconds}s...")
            time.sleep(sleep_seconds)
    raise RuntimeError("request retry loop ended unexpectedly")


def search_row(
    source: str,
    query: str,
    title: str,
    url: str,
    rank: int,
    result_count: int,
    snippet: str,
    seller: str = "",
    review_count: Any = "",
    collected_at: str = "",
) -> dict[str, Any]:
    row = {
        "source": source,
        "query": query,
        "title": title,
        "url": url,
        "rank": rank,
        "result_count": result_count,
        "search_volume": result_count,
        "snippet": snippet,
        "price": "",
        "currency": "",
        "seller": seller,
        "rating": "",
        "review_count": review_count,
        "collected_at": collected_at,
    }
    return enrich_record(row)


def product_row(
    source: str,
    product_id: str,
    title: str,
    url: str,
    category: str,
    stock_status: str,
    seller: str = "",
    review_count: Any = "",
    sales_volume: Any = "",
    last_updated: str = "",
    collected_at: str = "",
) -> dict[str, Any]:
    row = {
        "source": source,
        "product_id": product_id,
        "title": title,
        "url": url,
        "price": "",
        "currency": "",
        "seller": seller,
        "category": category,
        "stock_status": stock_status,
        "rating": "",
        "review_count": review_count,
        "sales_volume": sales_volume,
        "last_updated": last_updated,
        "collected_at": collected_at,
    }
    return enrich_record(row)


def producthunt_url(item: dict[str, Any]) -> str:
    path = item.get("url") or ""
    if not path:
        slug = item.get("slug")
        path = f"/posts/{slug}" if slug else ""
    return f"https://www.producthunt.com{path}" if path.startswith("/") else path


def write_csv(path: Path, columns: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        for row in rows:
            writer.writerow({column: row.get(column, "") for column in columns})


def read_csv_rows(path: Path | None) -> list[dict[str, Any]]:
    if path is None or not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def write_raw(raw_dir: Path, stamp: str, source: str, term: str, payload: Any) -> None:
    filename = f"{stamp}.{source}.{slug(term)}.json"
    path = raw_dir / filename
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def source_health(
    source: str,
    query: str,
    status: str,
    search_rows: int,
    product_rows: int,
    duration_seconds: float,
    error: str = "",
) -> dict[str, Any]:
    return {
        "source": source,
        "query": query,
        "status": status,
        "search_rows": search_rows,
        "product_rows": product_rows,
        "duration_seconds": duration_seconds,
        "error": error,
    }


def write_health_report(rows: list[dict[str, Any]], output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "source_health.json"
    csv_path = output_dir / "source_health.csv"
    markdown_path = output_dir / "source_health.md"
    json_path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
    write_csv(csv_path, ["source", "query", "status", "search_rows", "product_rows", "duration_seconds", "error"], rows)
    markdown_path.write_text(source_health_markdown(rows), encoding="utf-8")


def source_health_markdown(rows: list[dict[str, Any]]) -> str:
    by_source: dict[str, dict[str, Any]] = {}
    for row in rows:
        source = row.get("source", "")
        item = by_source.setdefault(
            source,
            {"ok": 0, "failed": 0, "skipped": 0, "unsupported": 0, "rows": 0, "seconds": 0.0},
        )
        status = str(row.get("status") or "")
        item[status] = item.get(status, 0) + 1
        item["rows"] += int(row.get("search_rows") or 0)
        item["seconds"] += float(row.get("duration_seconds") or 0)

    lines = [
        "# 数据源健康报告",
        "",
        "| 数据源 | 成功 | 失败 | 跳过 | 不支持 | 搜索行 | 耗时秒 |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for source, item in sorted(by_source.items()):
        lines.append(
            f"| {source} | {item.get('ok', 0)} | {item.get('failed', 0)} | "
            f"{item.get('skipped', 0)} | {item.get('unsupported', 0)} | "
            f"{item.get('rows', 0)} | {round(item.get('seconds', 0.0), 2)} |"
        )

    failures = [row for row in rows if row.get("status") not in {"ok"}]
    lines.extend(["", "## 失败明细", ""])
    if not failures:
        lines.append("没有失败。")
    else:
        for row in failures:
            lines.append(f"- {row.get('source')} / {row.get('query')}: {row.get('error')}")
    return "\n".join(lines) + "\n"


def github_issue_filter_config() -> dict[str, Any]:
    config = dict(DEFAULT_GITHUB_ISSUE_FILTER_CONFIG)
    config.update(GITHUB_ISSUE_FILTER_CONFIG or {})
    return config


def github_issue_fetch_limit(limit: int, filter_config: dict[str, Any]) -> int:
    base_limit = max(1, int(limit or 1))
    if not truthy(filter_config.get("enabled"), default=True):
        return base_limit
    overfetch_factor = max(1, int(filter_config.get("overfetch_factor") or 1))
    max_fetch = max(base_limit, int(filter_config.get("max_fetch_per_query") or base_limit))
    return min(100, max(base_limit, min(max_fetch, base_limit * overfetch_factor)))


def filter_github_issue_items(
    items: list[dict[str, Any]],
    filter_config: dict[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    if not truthy(filter_config.get("enabled"), default=True):
        return items, []

    kept: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    for item in items:
        should_keep, reasons = should_keep_github_issue(item, filter_config)
        if should_keep:
            kept.append(item)
        else:
            skipped.append(github_issue_skip_summary(item, reasons))
    return kept, skipped


def should_keep_github_issue(item: dict[str, Any], filter_config: dict[str, Any]) -> tuple[bool, list[str]]:
    if item.get("pull_request"):
        return False, ["pull_request"]

    user = item.get("user") or {}
    author = str(user.get("login") or "")
    if str(user.get("type") or "").lower() == "bot":
        return False, [f"bot_author:{author}"]

    author_hits = pattern_hits(config_patterns(filter_config, "extra_bot_author_patterns", GITHUB_ISSUE_BOT_AUTHOR_PATTERNS), author)
    if author_hits:
        return False, [f"bot_author:{author}"]

    title = clean(str(item.get("title") or ""))
    body = clean(str(item.get("body") or ""))
    labels = github_issue_labels(item)
    label_text = " ".join(labels)
    text = f"{title}\n{body}\n{label_text}"

    hard_hits = pattern_hits(config_patterns(filter_config, "extra_hard_noise_patterns", GITHUB_ISSUE_HARD_NOISE_PATTERNS), text)
    if hard_hits:
        return False, [f"hard_noise:{hit}" for hit in hard_hits[:3]]

    comments = int(item.get("comments") or 0)
    keep_if_comments = int(filter_config.get("keep_if_comments_at_least") or 0)
    demand_hits = pattern_hits(config_patterns(filter_config, "extra_demand_hint_patterns", GITHUB_ISSUE_DEMAND_HINT_PATTERNS), text)
    demand_label_hits = pattern_hits(config_patterns(filter_config, "extra_demand_label_patterns", GITHUB_ISSUE_DEMAND_LABEL_PATTERNS), label_text)
    has_explicit_demand_signal = bool(demand_hits or demand_label_hits)
    has_discussion_signal = bool(keep_if_comments and comments >= keep_if_comments)
    has_demand_signal = has_explicit_demand_signal or has_discussion_signal

    maintenance_hits = pattern_hits(
        config_patterns(filter_config, "extra_maintenance_noise_patterns", GITHUB_ISSUE_MAINTENANCE_NOISE_PATTERNS),
        text,
    )
    if maintenance_hits and not has_explicit_demand_signal:
        return False, [f"maintenance_noise:{hit}" for hit in maintenance_hits[:3]]

    noise_label_hits = pattern_hits(config_patterns(filter_config, "extra_noise_label_patterns", GITHUB_ISSUE_NOISE_LABEL_PATTERNS), label_text)
    if noise_label_hits and not has_explicit_demand_signal:
        return False, [f"noise_label:{hit}" for hit in noise_label_hits[:3]]

    if truthy(filter_config.get("require_demand_hint"), default=False) and not has_demand_signal:
        return False, ["missing_demand_hint"]

    return True, []


def github_issue_effective_total(
    api_total: Any,
    inspected_count: int,
    kept_count: int,
    filter_config: dict[str, Any],
) -> int:
    total = int(api_total or 0)
    if not truthy(filter_config.get("enabled"), default=True):
        return total or inspected_count
    if inspected_count <= 0 or kept_count <= 0:
        return kept_count

    strategy = str(filter_config.get("effective_total_strategy") or "sample_ratio")
    if strategy == "observed":
        return kept_count
    if strategy == "api_total":
        return total or kept_count

    base_total = total or inspected_count
    filtered_total = round(base_total * (kept_count / inspected_count))
    return max(kept_count, int(filtered_total))


def github_issue_skip_summary(item: dict[str, Any], reasons: list[str]) -> dict[str, Any]:
    user = item.get("user") or {}
    return {
        "title": item.get("title") or "",
        "url": item.get("html_url") or "",
        "author": user.get("login") or "",
        "labels": github_issue_labels(item),
        "comments": item.get("comments") or 0,
        "reasons": reasons,
    }


def github_issue_labels(item: dict[str, Any]) -> list[str]:
    labels = []
    for label in item.get("labels") or []:
        if isinstance(label, dict):
            name = str(label.get("name") or "").strip()
        else:
            name = str(label or "").strip()
        if name:
            labels.append(name)
    return labels


def config_patterns(filter_config: dict[str, Any], key: str, defaults: list[str]) -> list[str]:
    return list(defaults) + [str(pattern) for pattern in (filter_config.get(key) or []) if str(pattern).strip()]


def pattern_hits(patterns: list[str], value: str) -> list[str]:
    hits = []
    for pattern in patterns:
        try:
            matched = re.search(pattern, value or "", flags=re.IGNORECASE) is not None
        except re.error:
            matched = pattern.lower() in (value or "").lower()
        if matched:
            hits.append(pattern)
    return hits


def truthy(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() not in {"0", "false", "no", "off", ""}
    return bool(value)


def source_delay_seconds(source: str, default_delay: float, source_delays: dict[str, Any]) -> float:
    if not isinstance(source_delays, dict):
        return max(0.0, default_delay)
    value = source_delays.get(source, default_delay)
    try:
        return max(0.0, float(value or 0))
    except (TypeError, ValueError):
        return max(0.0, default_delay)


def source_failure_limit(source: str, default_limit: int, max_failures_by_source: dict[str, Any]) -> int:
    if not isinstance(max_failures_by_source, dict):
        return max(1, default_limit)
    value = max_failures_by_source.get(source, default_limit)
    try:
        return max(1, int(value))
    except (TypeError, ValueError):
        return max(1, default_limit)


def github_repo_from_issue(item: dict[str, Any]) -> str:
    repo_url = item.get("repository_url") or ""
    if not repo_url:
        return ""
    return repo_url.rstrip("/").rsplit("/", 2)[-2] + "/" + repo_url.rstrip("/").rsplit("/", 1)[-1]


def payload_items(payload: Any, *keys: str) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if not isinstance(payload, dict):
        return []
    for key in keys:
        value = payload.get(key)
        if isinstance(value, list):
            return [item for item in value if isinstance(item, dict)]
    nested = payload.get("response") or payload.get("results") or payload.get("data")
    if isinstance(nested, dict):
        for key in keys:
            value = nested.get(key)
            if isinstance(value, list):
                return [item for item in value if isinstance(item, dict)]
    return []


def payload_total(payload: Any, fallback: int) -> int:
    if not isinstance(payload, dict):
        return fallback
    for key in ("total", "count", "total_count", "num_found", "total_results"):
        value = payload.get(key)
        if value not in (None, ""):
            return int(float(value))
    nested = payload.get("response") or payload.get("metadata") or payload.get("pagination")
    if isinstance(nested, dict):
        for key in ("total", "count", "total_count", "num_found", "total_results"):
            value = nested.get(key)
            if value not in (None, ""):
                return int(float(value))
    return fallback


def first_present(item: dict[str, Any], *keys: str) -> Any:
    for key in keys:
        value = item.get(key)
        if value not in (None, ""):
            return value
    return ""


def safe_int(value: Any) -> int:
    if value in (None, ""):
        return 0
    try:
        return int(float(str(value).replace(",", "").strip()))
    except (TypeError, ValueError):
        return 0


def agentic_job_url(item: dict[str, Any]) -> str:
    for method in item.get("applyMethods") or []:
        if isinstance(method, dict) and method.get("value"):
            return str(method["value"])
    slug_value = str(first_present(item, "slug", "id"))
    if slug_value:
        return f"https://agentic-engineering-jobs.com/jobs/{slug_value}"
    return str(first_present(item, "companyWebsite", "url"))


def oksurf_items(payload: Any) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    items: list[dict[str, Any]] = []
    for category, values in payload.items():
        if not isinstance(values, list):
            continue
        for value in values:
            if isinstance(value, dict):
                row = dict(value)
                row["_category"] = category
                items.append(row)
    return items


def oksurf_text(item: dict[str, Any]) -> str:
    og = item.get("og") or {}
    og_text = json.dumps(og, ensure_ascii=False) if isinstance(og, dict) else str(og)
    return " ".join(
        str(value)
        for value in (
            item.get("title"),
            item.get("source"),
            item.get("_category"),
            og_text,
        )
        if value
    )


def oksurf_min_tokens(term: str) -> int:
    terms = query_terms(term)
    if terms == ["ai"]:
        return 1
    return max(1, min(2, len(terms)))


def api_status_matches(term: str, item: dict[str, Any]) -> bool:
    terms = query_terms(term)
    text = " ".join(
        str(value)
        for value in (
            item.get("name"),
            item.get("slug"),
            item.get("status"),
        )
        if value
    )
    if text_matches_query(term, text, min_tokens=min(2, max(1, len(terms)))):
        return True
    broad_match_allowed = "ai" in terms and bool(set(terms) & AI_SERVICE_STATUS_TERMS)
    return broad_match_allowed and str(item.get("category") or "").lower() == "ai"


AI_SERVICE_STATUS_TERMS = {"agent", "llm", "coding", "assistant", "search", "rag", "local", "api"}


def api_status_weight(status: str) -> int:
    lowered = (status or "").lower()
    if any(term in lowered for term in ("outage", "down", "major")):
        return 100
    if any(term in lowered for term in ("degraded", "partial", "minor", "incident")):
        return 60
    return 1


def archive_creator(item: dict[str, Any]) -> str:
    creator = item.get("creator")
    if isinstance(creator, list):
        return ", ".join(str(value) for value in creator[:3])
    return str(creator or "")


def nvd_matches(term: str, item: dict[str, Any]) -> bool:
    cve = item.get("cve") or {}
    terms = query_terms(term)
    text = " ".join(
        str(value)
        for value in (
            cve.get("id"),
            cve.get("sourceIdentifier"),
            nvd_description(cve),
            json.dumps(cve.get("weaknesses") or [], ensure_ascii=False),
        )
        if value
    )
    if text_matches_query(term, text, min_tokens=min(2, max(1, len(terms)))):
        return True
    lowered = text.lower()
    broad_ai_security_terms = {"agent", "llm", "coding", "assistant", "search", "rag"}
    broad_match_allowed = "ai" in terms and bool(set(terms) & broad_ai_security_terms)
    return broad_match_allowed and any(keyword in lowered for keyword in AI_SECURITY_TERMS)


AI_SECURITY_TERMS = (
    "openai",
    "anthropic",
    "chatgpt",
    "claude",
    "llm",
    "large language model",
    "machine learning",
    "artificial intelligence",
    "tensorflow",
    "pytorch",
    "hugging face",
    "huggingface",
    "langchain",
    "llamaindex",
    "vector database",
    "embedding",
    "rag",
)


def nvd_description(cve: dict[str, Any]) -> str:
    descriptions = cve.get("descriptions") or []
    for item in descriptions:
        if isinstance(item, dict) and item.get("lang") == "en":
            return clean(str(item.get("value") or ""))
    for item in descriptions:
        if isinstance(item, dict) and item.get("value"):
            return clean(str(item["value"]))
    return ""


def nvd_cvss(cve: dict[str, Any]) -> tuple[float, str]:
    metrics = cve.get("metrics") or {}
    for key in ("cvssMetricV40", "cvssMetricV31", "cvssMetricV30", "cvssMetricV2"):
        values = metrics.get(key) or []
        if not values:
            continue
        metric = values[0] if isinstance(values[0], dict) else {}
        data = metric.get("cvssData") or {}
        score = float(data.get("baseScore") or metric.get("baseScore") or 0)
        severity = str(data.get("baseSeverity") or metric.get("baseSeverity") or "")
        return score, severity
    return 0.0, ""


def devitjobs_text(item: dict[str, Any]) -> str:
    keys = (
        "name",
        "company",
        "techCategory",
        "metaCategory",
        "workplace",
        "remoteType",
        "actualCity",
        "cityCategory",
        "stateCategory",
        "companyType",
    )
    return " ".join(
        [str(item.get(key) or "") for key in keys]
        + [str(value) for value in item.get("technologies") or []]
        + [str(value) for value in item.get("perkKeys") or []]
    )


def devitjobs_min_tokens(term: str) -> int:
    terms = query_terms(term)
    if "ai" in terms:
        return 1
    return max(1, min(2, len(terms)))


def devitjobs_url(slug_value: str) -> str:
    if not slug_value:
        return ""
    if slug_value.startswith("http://") or slug_value.startswith("https://"):
        return slug_value
    return "https://devitjobs.us/jobs/" + slug_value.lstrip("/")


def predscope_text(item: dict[str, Any]) -> str:
    outcomes = item.get("outcomes") or []
    outcome_text = " ".join(str(outcome.get("title") or "") for outcome in outcomes if isinstance(outcome, dict))
    return " ".join(
        str(value)
        for value in (
            item.get("title"),
            item.get("slug"),
            " ".join(str(category) for category in item.get("categories") or []),
            outcome_text,
        )
        if value
    )


def predscope_min_tokens(term: str) -> int:
    terms = query_terms(term)
    if "ai" in terms:
        return 1
    return max(1, min(2, len(terms)))


def predscope_top_outcome(item: dict[str, Any]) -> str:
    outcomes = [outcome for outcome in item.get("outcomes") or [] if isinstance(outcome, dict)]
    if not outcomes:
        return ""
    top = max(outcomes, key=lambda outcome: float(outcome.get("probability") or 0))
    probability = top.get("probability")
    if probability not in (None, ""):
        return f"{top.get('title')} ({round(float(probability) * 100, 1)}%)"
    return str(top.get("title") or "")


def query_terms(term: str) -> list[str]:
    return [
        value
        for value in re.findall(r"[a-z0-9][a-z0-9+#.\-]*", (term or "").lower())
        if value
    ]


def text_matches_query(term: str, text: str, min_tokens: int | None = None) -> bool:
    terms = query_terms(term)
    if not terms:
        return False
    lowered = (text or "").lower()
    phrase = " ".join(terms)
    if phrase and phrase in lowered:
        return True
    hits = [
        token
        for token in terms
        if re.search(rf"(?<![a-z0-9]){re.escape(token)}(?![a-z0-9])", lowered)
    ]
    if min_tokens is None:
        min_tokens = len(terms) if len(terms) <= 2 else max(2, len(terms) - 1)
    return len(hits) >= max(1, min_tokens)


def domain_search_term(term: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "", term.lower())
    return cleaned or slug(term)


def slug(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return cleaned or "query"


def clean(value: str) -> str:
    return " ".join((value or "").split())


def _timestamp_to_iso(value: Any) -> str:
    if value in (None, ""):
        return ""
    try:
        return datetime.fromtimestamp(float(value), tz=timezone.utc).isoformat()
    except (TypeError, ValueError, OSError):
        return ""


def _strip_tags(value: str) -> str:
    return re.sub(r"<[^>]+>", " ", value or "")


def _parse_rss_date(value: str) -> str:
    if not value:
        return ""
    try:
        from email.utils import parsedate_to_datetime

        parsed = parsedate_to_datetime(value)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed.astimezone(timezone.utc).isoformat()
    except (TypeError, ValueError, IndexError):
        return value


if __name__ == "__main__":
    raise SystemExit(main())
